### ISSUE TITLE
The 'Show Zero' switch on the Material UI Badge page works incorrectly

### ISSUE THREAD

**Issue by eugenekuzn** [jdi-testing/jdi-light#3615]
The "Show Zero" switch must display the badge with "0" value when it is turned on, but instead, it hides the badge and shows it when the switch is turned off. 

![image](https://user-images.githubusercontent.com/54530676/146015861-7aebacd6-72c3-4c65-9b54-86c7e921d903.png)
![image](https://user-images.githubusercontent.com/54530676/146015910-89f0d313-fd8e-4237-b708-16c0303caa68.png)

Steps:
1. Open [Material UI Badge page](https://jdi-testing.github.io/jdi-light/material/badge)
2. Click the "Minus" button until badge value is 0
3. Turn on "Show Zero" switch

Expected result: 
The badge disappears when the badge's value is 0 and appears when switch is turned on

Actual result: 
The badge disappears when the switch is turned on

**Comment by cold-flame** [comment]
Add commit to gh-pages-material branch
Need create PR to master

**Comment by AlexeyGirin** [comment]
Done.

**Comment by MaksimGudovich** [comment]
Issue is not fixed.
When the "Show Zero" switch is off, the badge with value  "0" should disappear and reappear when the switch is on.
